name: gospl-smoker
channels:
  - conda-forge
  - geodels
  - nodefaults
dependencies:
  - python=3.11
  - numpy<2
  - gospl=2026.6.30
  - gmt
  - pygmt
  - hdf4
  - libnetcdf
  - hdf5
  - netcdf4
  - vtk
  - scipy
  - pandas
  - matplotlib
  - xarray
  - h5py
  - mpi4py
  - petsc
  - petsc4py
  - pyshtools
  - meshio
  - geopandas
  - cartopy
  - rasterio
  - numba
  - pyyaml
  - pyinterp
  - esmpy
  - uxarray
  - jigsawpy
  - triangle
  - jupyterlab
  - ipywidgets
  - ipykernel
  - mpas_tools
  - rioxarray
  - xesmf