name: gospl-smoke
channels:
  - conda-forge
  - geodels
  - nodefaults
dependencies:
  - python=3.11
  - numpy<2
  - gospl=2026.6.13
  - gmt
  - pygmt
  - hdf4
  - libnetcdf
  - hdf5
  - netcdf4
  - vtk
  - scipy
  - pandas
  - matplotlib
  - xarray
  - h5py
  - mpi4py
  - petsc
  - petsc4py
  - pyshtools
  - meshio
  - pyvista
  - cartopy
  - rasterio
  - pyproj
  - geopandas-base
  - shapely
  - scikit-image
  - numba
  - dask
  - pooch
  - tqdm
  - pyyaml
  - pyevtk
  - pyinterp
  - healpix
  - gflex
  - esmpy
  - uxarray
  - jigsawpy
  - inpoly
  - triangle
  - pyshp
  - jupyterlab
  - ipywidgets
  - ipykernel
  - mpas_tools
  - rioxarray
  - xesmf