name: gospl-smoke
channels:
  - conda-forge
dependencies:
  - pyinterp
  - pyproj 
  - triangle
  - netcdf4
  - xarray
  - rioxarray
  - uxarray
  - jigsawpy
  - xesmf
  - mpas_tools
  - pygmt
  - rasterio
  - numba
  - shapely
  - pip:
    - pysheds